version: '3.8'

services:
  gradio:
    build: .
    container_name: gradio
    ports:
      - 7860:7860
    environment:
      SERVER_VPS1_IP : ${SERVER_VPS1_IP:?error}
      ARM_VPS1_API_KEY : ${ARM_VPS1_API_KEY:?error}
    networks:
      - production-network
    labels:
      - traefik.http.routers.gradio.rule=PathPrefix(`/gradio`)

networks:
  production-network:
    name: production-network
    external: true
