services:
  mlflow:
    build: .
    container_name: mlflow
    ports:
      - 5000:5000
    volumes:
      - ../../volumes/mlflow/mlruns:/mlflow/mlruns 
      - ../../volumes/mlflow/mlartifacts:/mlflow/mlartifacts
    networks:
      - production-network
    labels:
      # - traefik.http.routers.mlflow.rule=PathPrefix(`/mlflow`)
      - traefik.http.routers.mlflow.tls=true

networks:
  production-network:
    name: production-network
    external: true
