version: '3.8'

services:
  mlflow:
    build: .
    container_name: mlflow
    ports:
      - 5000:5000
    networks:
      - production-network
    labels:
      - traefik.http.routers.mlflow.rule=PathPrefix(`/mlflow`)
  # mariadb:
  #   image: mariadb:10.11.5
  #   container_name: mariadb
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${PWD_MARIADB:?error}
  #     MYSQL_DATABASE: IA_metadata
  #   volumes:
  #     - ../../volumes/mariadb/ia:/var/lib/mysql:Z
  #     - ../../volumes/mariadb/ia-backup:/backup
  #   ports:
  #     - "3307:3307"  # Port MariaDB
  #   networks:
  #     - production-network

networks:
  production-network:
    name: production-network
    external: true
